### ISSUE TITLE
Taking any damage causes "Teleportation Cancelled" message to display

### ISSUE THREAD

**Issue by Sepshun** [AtriusX/Waystones#10]
When taking any form of damage, the "Teleportation cancelled" message shows, despite not having a teleportation queued.
This was happening prior to the restructure and the fix in 45db3e31eff3e4de9789c81d58b74c7e86e50eeb didn't get moved over it seems.

**Comment by AtriusX** [comment]
This should be fixed via 144be5dd9e45a15cb6595ed76b0960e302c779ab now.

**Comment by Sepshun** [comment]
It has indeed been fixed! 👍🏻
