### ISSUE TITLE
Error while enabling Waystones

### ISSUE THREAD

**Issue by SneakyMini** [AtriusX/Waystones#2]
So I downloaded your repository and built the .jar file manually, (after some research because i never worked with gradle) and now when trying to start the server, the plugin isn't loaded correctly (I built the .jar on windows but that shouldn't be an issue afaik)
![Screenshot 2021-02-17 113949](https://user-images.githubusercontent.com/49494673/108192704-e3cbc900-7114-11eb-90fe-e885d74cf11f.png)

**Comment by AtriusX** [comment]
Thanks for your report and apologies for the late reply. Looking at the stack trace it appears that the plugin was compiled without Kotlin. You likely compiled the plugin using the build task under gradle, which doesn't include the dependency in the jar as needed. To resolve this you should instead build the plugin using the shadowJar gradle task instead. 

Hopefully this resolves the problem. Let me know if you encounter any other issues!
