### ISSUE TITLE
Global warps

### ISSUE THREAD

**Issue by RedSmarty** [AtriusX/Waystones#20]
Is it possible for you to add a /warp command which opens a gui that lists all the warps player has discovered, and allow to tp to those warps.
You can check my other feature request to see how can you implement discovering of these warps. You can also add a /addwarp command that enables us to add a particular warp to a player warp list.You can make it so server owners can select the icon of the warp(with player skull and custom model data support).

**Comment by AtriusX** [comment]
As mentioned on #19 I personally believe this is beyond the scope of the plugin. Something like this I feel would be much better geared for placing in a secondary plugin which uses Waystones as a dependency. 

While the API may or may not fully exist to facilitate this yet I would be interested in hearing what sort of information Waystones would need to provide.

**Comment by AtriusX** [comment]
Closing this issue now, any discussion in regard to the plugin's API should be directed to discussion #22.
