### ISSUE TITLE
Key Item Crafting Recipe

### ISSUE THREAD

**Issue by NathanAdhitya** [AtriusX/Waystones#26]
Hello, it seems like the actual crafting recipe is hard to find. Including it as an image in the README would help a lot. Having it shoved deep in the code seems quite challenging to find https://github.com/AtriusX/Waystones/blob/master/src/main/kotlin/xyz/atrius/waystones/data/crafting/CompassRecipe.kt

Furthermore, we'd like to see being able to actually customize the crafting recipe to our own needs.
Thank you.

**Comment by AtriusX** [comment]
Thanks for your input! I agree that the crafting recipe should be listed in the README. I also agree that the crafting recipe should be configurable, and I do have a possible solution for that, but I'm not completely sure whether it will work nicely enough or not. 

What I'm currently thinking is a list of material types is listed in the config (possibly either of size 1, 4, or 9) which is parsed into material types and built into a recipe. I am currently unsure if there is a better way to approach this or not, or if other functionality is desired as well though. If you have any other requests related to this I'm open to hearing them. Thanks!
