### ISSUE TITLE
Inconsistent ConfigCommand regarding values with PercentageParser

### ISSUE THREAD

**Issue by Sepshun** [AtriusX/Waystones#9]
Config values with a PercentageParser applied require a percentage symbol after the value when setting them through ConfigCommand, though this is never displayed by the command itself when listing values.

Strangely, trying to the `portal-sickness-chance` value to `0.05%`, which is its default and is followed by a percentage sign, still fails for an unknown reason, as setting it to `0.01%` works fine.

**Comment by AtriusX** [comment]
That seems to be a bit of a weird behavioral problem. The formatter is primarily designed to take in solid numbers with a percent symbol (primarily 5% or 65%, etc.) but I can see why someone would want to use decimal places for it.

I've come  up with a bit of a solution for this though I think:

```kt
	// ...

    fun parse(input: String?): T?

    fun toString(value: T): String =
        value.toString()
}
```
```kt
object PercentageParser : ArgumentParser<Double> {
    private val regex = "^[0-9]+(.[0-9]+)?%$".toRegex()

    override fun parse(input: String?): Double? =
        if (input?.matches(regex) == true)
            input.dropLast(1).toDouble() / 100 else null

    override fun toString(value: Double): String =
        "${value * 100}%"
}
```
The percentage parser should now be able to offer a formatting override, additionally the regex matcher now covers the entire input and supports decimal places.

**Comment by AtriusX** [comment]
@Sepshun This should be pushed to the commands branch now. See 4ab28679b55ca378cd777720838143dafa44e68a and de870d1d99b1d6fc3c20cdc2690ec6dd64612a82. Would appreciate testing on this.

**Comment by Sepshun** [comment]
Works as intended! Values with and without percentage symbols or decimals can be used through the command, and listing the values shows the proper percentage value.
